Day 52 Revert Deployment to Previous Version in Kubernetes

Earlier today, the Nautilus DevOps team deployed a new release for an application. However, a customer has reported a bug related to this recent release. Consequently, the team aims to revert to the previous version.


There exists a deployment named nginx-deployment; initiate a rollback to the previous revision.

Note: The kubectl utility on jump_host is configured to interact with the Kubernetes cluster.

Solution:

#check current deployment
kubectl describe deployment nginx-deployment

#check rollout history
kubectl rollout history deployment/nginx-deployment

#rollback to Previous
kubectl rollout undo deployment/nginx-deployment

#watch rollback progress
kubectl rollout status deployment/nginx-deployment

#verify
kubectl describe deployment nginx-deployment | grep Image

#checking pods running
kubectl get pods
